{
    "name"      : "Odoo Sample Module",
    "description"   : "Módulo de exemplo do Odoo.",
    "summary"   : "",
    "category"  : "Sample",
    "version"   : "19.0.0.0",
    "author"    : "Eduardo Luiz",
    "website"   : "",
    "company"   : "e-Masters Tecnologia",
    "maintainer": "e-Masters Tecnologia",
    "license"   : "LGPL-3",
    "depends"   : ["base", "mail"],
    "data":
        [
            "security/ir.model.access.csv",
            "views/app.xml",
            "views/get_started_model_view.xml",
            "views/metodo_pagamento_view.xml",
            "views/sample_model_view.xml",
            "views/perfil_view.xml",
            "views/perfil_valores_view.xml",
            "views/pessoa_view.xml",
            "views/casa_view.xml",
            "views/conta_view.xml",
            "views/unidade_organizacional_view.xml",
            "views/forecast_view.xml",
            "views/forecast_itens_view.xml",
        ],
    "assets"    : {},
    "qweb"      : [],
    "images"    : [],
    "installable"   : True,
    "application"   : True,
    "auto_install"  : False,
}